baseURL = "http://hazellanes.github.io/"
title = "hazelLanes"
theme = "slick"
languageCode = "en-us"

[params]
  subtitle = "Banal musings on various inconsequentialities."
  description = "Yodur site description"
  copyright = ""

  css = "custom.css"
  
  dateFmt = "2006-01-02"
  showFullContent = false
  showMetaDates = true
  showMetaLinks = true
  

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
