#+title: UVG Classes
#+date: 2020-06-16
#+draft: true

* Fighter
*Starting Equipment:* leather armor, random military melee weapon (1d10, UVG pg. 173), random ranged weapon (1d4, UVG pg. 172).

*A:* Parry, +1 attack per round \\
*B:* Notches \\
*C:* Quick Learner, +2 to Attack rolls \\
*D:* Impress, Cleave

You gain +1 Grit for each Fighter template you possess.

** A: Parry
Once per day you can reduce incoming damage by 1d12 points.
If you also choose to sunder a shield, you can reduce the
damage by 12 points instead of 1d12.

** B: Notches
Each time you attain a total of 10, 20, 30, and 50 kills with a
weapon type (such as 10 kills with a dagger), you unlock a new
ability for that weapon, chosen from the list below. Keep track of
your kills and special abilities on the back of your character
sheet.

- +1 Damage
- Expanded critical range (-1)
- Special ability (negotiated with GM, one per weapon)

** C: Quick Learner
You can become proficient with a new weapon after 4 successful
hits (instead of 8). If your first attack is a critical hit, you
immediately become proficient.

** D: Impress
Whenever you win a fight against challenging foes, people who
don't like you make a new reaction roll with a +4 bonus. This
even works on people you just defeated in combat, unless you
caused them undeserved or disproportionate harm. Hirelings get
a +2 to Morale or a new Save vs Fear.

** D: Cleave
Whenever you reduce a creature to 0 HP with an attack, you can
make another attack with the same weapon against a target
within 5’. You can only cleave an number of targets equal to your
Level in a single round.

-----

* Barbarian
*Starting Equipment:* leather armor, simple melee weapon (1d18, UVG pg. 173), weird melee weapon (1d6, UVG pg. 173)

*A:* Rage \\
*B:* Danger Sense, A Taste of Home \\
*C:* Feat of Strength, Die Hard \\
*D:* Tough

You gain +2 Grit for each Barbarian template you possess.

** A: Rage
You can choose to enter a rage at the start of your turn, or in response to taking damage. You might froth, or stare in battle-focus, or merely let a facade drop and give in to your ancient urges, brutal warrior training, or religious fanaticism.

While in a rage:
- You gain +4 to Wisdom for Initiative purposes. You act before all other PCs in a round.
- You gain +1 attack per round.
- All your melee attacks inflict +1 damage.
- You can only cast damaging spells. All your spells deal +2 damage (if single target) or +1 damage (if multiple targets).
- You are immune to pain and fear.
- You cannot do anything defensive, curative, or tactical with your allies. All you can do is attempt to kill things.

You cannot stop fighting until you kill, subdue, or drive off all
enemies. If an ally has injured you this fight, they count as an
enemy. To stop raging, check WIS at the start of your turn.

** B: Danger Sense
If you are surprised, you have a 50% chance to act in the
surprise round anyway. If you encounter a creature no one in the
group has seen before, you can roll under Intelligence to
remember a detail or weakness, provided the creature is not
unique.

** B: A Taste of Home
You can consume a special ration or drug to regain 1d6+1 HP.
This takes 1 round. One “dose” costs 30 cash and can be
purchased in any trading city. 3 doses fit in a single inventory
slot. You cannot eat while raging, but you can immediately enter
a rage after eating the ration. If you have any Lethal Damage,
you instead heal to 0 HP. If an ally waves the ration under you
nose, you can roll under Constitution to wake up.

** C: Feat of Strength
Once per day, you have 22 Strength for 1 round.

** C: Die Hard
You have 4 rounds instead of 3 to remove all of your Fatal Wounds.

** D: Tough
Reduce all incoming damage by 1 point. Gain +2 to Save vs. Mind Altering Effects.

* Thief
*Starting Equipment:* leather armor, lockpicks, 3 daggers, 1 starting skill: "Locksmith"
